### ISSUE TITLE
Someone is name squatting

### ISSUE THREAD

**Issue by timkpaine** [quantopian/empyrical#105]
https://pypi.org/project/empyrical3/
https://github.com/santosjorge/cufflinks/issues/145

**Comment by timkpaine** [comment]
heres the non-forked repo:
https://github.com/liudengfeng/empyrical3

**Comment by twiecki** [comment]
The copyright was removed: https://github.com/liudengfeng/empyrical3/commit/7d39d099799c63c61f6b0be5396c4c59cf333f3a#diff-9879d6db96fd29134fc802214163b95aR189

**Comment by timkpaine** [comment]
removed from pypi, will let you guys pursue copyright stuff if desired

**Comment by jikquantopian** [comment]
Project has been removed from Github as well, so copyright changes are no longer an issue.
