### ISSUE TITLE
Support Python >3.5

### ISSUE THREAD

**Issue by seanlseymour** [quantopian/empyrical#113]
Installing fails using Python 3.6 and later as provided in current conda distribution. Bottleneck package dependency seems to fail to install.

**Comment by cgdeboer** [comment]
I'd love to see the requirement for `bottleneck` fall off. Packages consumers can still use it, and the codebase is already set up to eagerly load it if available in the environment, else fall back to numpy. 

@twiecki and team, open to maintaining bottleneck support but dropping it as a requirement ? We've seen some packaging issues with it (off an on) over the years.

**Comment by twiecki** [comment]
Yes, should be optional.

**Comment by cgdeboer** [comment]
@seanlseymour I may work on a PR later this week, unless you have already started on it.

**Comment by seanlseymour** [comment]
No, I haven’t started anything here. Would appreciate!

Sean

**Comment by seanlseymour** [comment]
Thank you!

**Comment by qwhelan** [comment]
@cgdeboer I'm new maintainer of bottleneck and would appreciate it if you could open an issue with some details on the packaging issues you've encountered, as the upcoming release of 1.3.0 should solve them: https://github.com/pydata/bottleneck
