### ISSUE TITLE
Remove Series.strides from codebase (Pandas deprecation)

### ISSUE THREAD

**Issue by cgdeboer** [quantopian/empyrical#114]
#### Summary
Pandas 0.24 (or 0.23) deprecates the `strides` attribute of `Series` which is used in this repository. https://pandas.pydata.org/pandas-docs/version/0.24/whatsnew/v0.23.0.html?highlight=strides#deprecations

#### Tasks
- [ ] update the utils to handle the deprecation of the `strides` attribute.

**Comment by twiecki** [comment]
Thanks, want to do a PR?

**Comment by cgdeboer** [comment]
@twiecki I may work on this and #113 over the next week or two.
