### ISSUE TITLE
ImportError: cannot import name 'information_ratio' from 'empyrical'

### ISSUE THREAD

**Issue by sokol11** [quantopian/empyrical#127]
This is still an issue with the latest pyfolio / empyrical install (0.5.3)

**Comment by richafrank** [comment]
Hi @sokol11 , `information_ratio` was removed from empyrical and then from [pyfolio in v0.8.0](https://github.com/quantopian/pyfolio/commit/a34222e6a065b85147e9e7e53cce4549058bd51e) (released Aug 23, 2017). It sounds like you have an old version of pyfolio that still depends on `information_ratio`. 

Feel free to open a new issue in pyfolio or zipline if their latest versions still have this problem!
