### ISSUE TITLE
BUG: beta does not work with pandas Series

### ISSUE THREAD

**Issue by twiecki** [quantopian/empyrical#23]
It seems like whatever gets returned by `np.intersect1d()` is not possible to use as the index of a `pandas.Series()`. It only returns `nans`.

**Comment by twiecki** [comment]
Instead I used `indices = pd.concat([returns, factor_returns]).dropna().index`

**Comment by ahgnaw** [comment]
https://github.com/quantopian/empyrical/compare/bug-23?expand=1

**Comment by ahgnaw** [comment]
https://github.com/quantopian/empyrical/pull/26
