### ISSUE TITLE
Add conda builds

### ISSUE THREAD

**Issue by twiecki** [quantopian/empyrical#34]
We have a quantopian conda channel. Empyrical should be part of it so that our zipline and pyfolio conda builds can depend on it.

**Comment by richafrank** [comment]
The zipline travis and appveyor jobs are currently building empyrical conda packages and uploading them to https://anaconda.org/Quantopian/empyrical/files.  Is that good enough?

**Comment by twiecki** [comment]
Can we add pyfolio to that?

**Comment by richafrank** [comment]
To me, the zipline build doesn't feel like quite the right medium for building pyfolio packages.  

- Right now the zipline jobs build conda packages for the versions of zipline that they test (currently 2.7 and 3.4).  I believe pyfolio has historically run ahead of zipline in its support of newer python/numpy/pandas, so probably we'd only build pyfolio packages for those configurations that zipline supports?
- The zipline jobs currently build conda packages only for zipline and zipline's dependencies, and this process adds a bunch of time to each job.  I'd prefer not to have zipline developers waiting while their branch also builds packages that zipline doesn't need.

What do you think about having the pyfolio job build pyfolio packages (and any missing packages for its dependencies, e.g. empyrical), in the same way that zipline does?

**Comment by twiecki** [comment]
That makes sense. Alternatively, we can add pyfolio to conda-forge. Ultimately I think we should move zipline and empyrical too, but pyfolio could be a good trial run.

**Comment by richafrank** [comment]
That's a good idea.  One feature that conda-forge wouldn't give us is CI of the packaging process, which I think has been valuable for zipline.  But if the packaging of pyfolio usually works, and it's ok to wait for a release to package, then conda-forge is probably enough.

**Comment by twiecki** [comment]
https://github.com/quantopian/pyfolio/issues/342

**Comment by yuqli** [comment]
Sorry but I am new to here and was trying to install pyfolio through conda. It seems the package is not in Quantopian channel on conda? Just wondering how to do this. 

Last time I used pip install pyfolio and seemed there were some conflicts with matplotlib and I never solved that. Just in case I am making a similar mistake this time. Thanks!
