### ISSUE TITLE
Ensure max_drawdown returns a float scalar

### ISSUE THREAD

**Issue by avi-analytics** [quantopian/empyrical#43]
max_drawdown promises to return a float scalar in it's documentation;  however in reality it returns an ndarray/Series object with same dimensionality as the input. This creates problem in 'calmar_ratio' as the 'if max_dd<0:' statement throws "Truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()" exception.

**Comment by twiecki** [comment]
@avi-analytics Thanks! Want to submit a PR that fixes this?

**Comment by richafrank** [comment]
Mystery solved in https://github.com/quantopian/empyrical/pull/45#issuecomment-299338946
