### ISSUE TITLE
Add Additional Calculations & Rolling Periods

### ISSUE THREAD

**Issue by cgdeboer** [quantopian/empyrical#46]
@twiecki and friends, I'm working on the project that requires many of the same calculations that are performed in this repo, but also several others.  I am starting to work on a PR to add a variety of other statistical measures as well as a framework for getting rolling metrics on those things. 

Here are a few examples of additional metrics: `up-capture`, `down-capture`, `tracking-error`.

Would like to add some ability to create rolling metrics. eg: `Rolling 60-day Max Drawdown`, `Rolling 12 month Tracking Error` 

Before I start this work in earnest, I want to ensure that you all are open to expanding the calculation and capability set. Also, I can include a correct calculation of information ratio.

**Comment by twiecki** [comment]
@cgdeboer That would be much appreciated and we'd be more than happy to work with you on this.

**Comment by cgdeboer** [comment]
Great ! I'll post an initial PR tomorrow or early next week as a "Work In Progress" so I can get some initial thoughts from  you.
