### ISSUE TITLE
AttributeError: 'str' object has no attribute 'year'

### ISSUE THREAD

**Issue by kmikael** [quantopian/empyrical#53]
I do: `empyrical.aggregate_returns(spy, convert_to=empyrical.YEARLY)` where `spy` is just a `Series` of `SPY` which works with all the other `empyrical` functions. 

I always get the following error:

```
    192         grouping = [lambda x: x.year, lambda x: x.month]
    193     elif convert_to == YEARLY:
--> 194         grouping = [lambda x: x.year]
    195     else:
    196         raise ValueError(

AttributeError: 'str' object has no attribute 'year'
```

Tis also happens with `WEEKLY` and `MONTHLY`.

Am I missing something or is this a bug?

**Comment by ssanderson** [comment]
@kmikael what's the dtype of `spy.index`?  It looks to me like you're passing data with an index of strings, but we're expecting a `DatetimeIndex`.

**Comment by kmikael** [comment]
@ssanderson That was exactly it, thanks. I was reading csv files and not parsing the dates.
