### ISSUE TITLE
Standard Deviation: Sample vs. Population

### ISSUE THREAD

**Issue by yehoshuadimarsky** [quantopian/empyrical#54]
The code for annual_volatility and the related Sharpe ratio and others uses the numpy `std `function. However, the source code automatically sets `ddof=1`, which if I understand correctly is appropriate if the data is a sample. However, I am using data that is the entire population, so I need to set `ddof` to 0. It would be nice if we could add that as an option in the higher level functions.

Source: http://www.statsdirect.com/help/basics/degrees_freedom.htm

**Comment by twiecki** [comment]
Thanks for your request. You always just have a sample from some underlying distribution. I understand you might still want it but we won't put it into empyrical.
