### ISSUE TITLE
cannot concatenate a non-NDFrame object

### ISSUE THREAD

**Issue by JohnnyPP** [quantopian/empyrical#71]
Running:

import numpy as np
from empyrical import max_drawdown, alpha_beta

returns = np.array([.01, .02, .03, -.4, -.06, -.02])
benchmark_returns = np.array([.02, .02, .03, -.35, -.05, -.01])

# calculate alpha and beta
alpha, beta = alpha_beta(returns, benchmark_returns)

Gives "cannot concatenate a non-NDFrame object" error

**Comment by twiecki** [comment]
These need to be `pandas.Series` objects with proper datetime index.

**Comment by dmichalowicz** [comment]
Is this still an issue?

**Comment by twiecki** [comment]
Probably not.
