### ISSUE TITLE
Should returns be lognormal or normal

### ISSUE THREAD

**Issue by rsheftel** [quantopian/empyrical#73]
In the comments for the stats.cum_returns() function it states:

    Notes
    -----
    For increased numerical accuracy, convert input to log returns
    where it is possible to sum instead of multiplying.

But the math of function itself does not sum the returns but rather multiplies each return. So the notes state that log returns should be provided, but the math assumes normal returns. This is confusing, which should it be?

**Comment by rsheftel** [comment]
I answered my own question, all returns are normal (simple). If there are no objections I will submit a PR that removes the confusing comments.

**Comment by ssanderson** [comment]
I think the intent of this docstring is to encourage users to not use this function if numerical precision is a concern, rather than trying to emply that the function expects log returns.  Agreed that this is worded confusingly.

**Comment by rsheftel** [comment]
Now that #82 is merged, this can be closed.
