### ISSUE TITLE
not able to use skew or kurtosis

### ISSUE THREAD

**Issue by ruhkog** [quantopian/empyrical#95]
Looking at your stats.py code (see below), I see that you have the skew and kurtosis. However, I am not able to use it using empyrical. 

SIMPLE_STAT_FUNCS = [
    cum_returns_final,
    annual_return,
    annual_volatility,
    sharpe_ratio,
    calmar_ratio,
    stability_of_timeseries,
    max_drawdown,
    omega_ratio,
    sortino_ratio,
    stats.skew,
    stats.kurtosis,
    tail_ratio,
    cagr,
    value_at_risk,
    conditional_value_at_risk,
]

**Comment by richafrank** [comment]
Hi @ruhkog , those are attributes of the `scipy.stats` module imported at the top of `empyrical.stats`. Have you tried importing those functions from `scipy.stats`?

**Comment by ruhkog** [comment]
I ended up doing this! Thanks

**Comment by richafrank** [comment]
Great!
